import pygame

# RGB COLOR
COLOR_WHITE = (255, 255, 255)
COLOR_BLACK = (0, 0, 0)
COLOR_GREY = (195, 195, 195)
COLOR_WOOD_BROWN = (208, 161, 115)
COLOR_BLUE = (0, 0, 255)
COLOR_RED = (255, 0, 0)
COLOR_WHITE_VANILLA = (244, 240, 220)

# BOARD SIZE 
ROWS, COLS = 20, 20 
SQUARE_SIZE = 35 

BUTTON_WIDTH = 125
BUTTON_HEIGHT = 45

CENTER_CIRCLE_RADIUS = 8

BOARD_WIDTH = COLS * SQUARE_SIZE
BOARD_HEIGHT = ROWS * SQUARE_SIZE
BOARD_COLOR = COLOR_WHITE_VANILLA

# WINDOW
BORDER_SIZE = 45
LINE_WIDTH = 2
WINDOW_WIDTH = BORDER_SIZE + BOARD_WIDTH + BORDER_SIZE
WINDOW_HEIGHT = BORDER_SIZE + BOARD_HEIGHT + BORDER_SIZE + BUTTON_HEIGHT + BORDER_SIZE
WINDOW_TITLE = 'Gomoku'

# CELL
CELL_BORDER = 2
O_RADIUS = SQUARE_SIZE/2 - CELL_BORDER
O_LINE_THICKNESS = 2
X_LINE_THICKNESS = 2
